### ISSUE TITLE
Migration to QGIS 3.0

### ISSUE THREAD

**Issue by mtravis** [mtravis/gridref-qgis#22]
You had a go at this yet? I've tried running the 2to3 script on this plugin but it keeps giving me this error.

Traceback (most recent call last):
  File "C:\Users\mtravis\.qgis2\python\plugins\2to3.py", line 7, in <module>
    sys.exit(main('qgis_fixes'))
  File "C:\Python27\lib\lib2to3\main.py", line 221, in main
    avail_fixes = set(refactor.get_fixers_from_package(fixer_pkg))
  File "C:\Python27\lib\lib2to3\refactor.py", line 108, in get_fixers_from_package
    for fix_name in get_all_fix_names(pkg_name, False)]
  File "C:\Python27\lib\lib2to3\refactor.py", line 35, in get_all_fix_names
    pkg = __import__(fixer_pkg, [], [], ["*"])
ImportError: No module named qgis_fixes

**Comment by tomchadwin** [comment]
I didn't use the 2to3 script. I decided to branch off QGIS2, then in master, correct each error as it came up as I tested.

**Comment by mtravis** [comment]
Ah ok. Might be the simplest way with this plugin.

**Comment by tomchadwin** [comment]
Have you also seen this page:

https://github.com/qgis/QGIS/wiki/Plugin-migration-to-QGIS-3

**Comment by mtravis** [comment]
Yes thanks @tomchadwin. I've been following the steps from there.
